# Generated by Django 2.1.7 on 2019-03-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20190308_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='cover',
            field=models.ImageField(default='all_covers/cover.jpg', upload_to='all_covers/'),
        ),
    ]
