# Generated by Django 2.1.7 on 2019-03-16 10:28

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_auto_20190309_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='ratings',
        ),
        migrations.AddField(
            model_name='reviews',
            name='the_json',
            field=jsonfield.fields.JSONField(default={'1': 0, '2': 0, '3': 0, '4': 0, '5': 0}, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='cover',
            field=models.ImageField(default='all_covers/cover.jpg', upload_to='all_covers/'),
        ),
    ]
