# Generated by Django 2.1.7 on 2019-03-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_auto_20190316_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='the_json',
            new_name='ratings',
        ),
    ]
