# Generated by Django 2.1.7 on 2019-03-16 10:45

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_auto_20190316_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='ratings',
            field=jsonfield.fields.JSONField(default={'1': 0, '2': 0, '3': 0, '4': 0, '5': 0}),
        ),
    ]
