# Generated by Django 2.1.7 on 2019-03-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0007_auto_20190316_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='average',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
