# Generated by Django 2.1.7 on 2019-03-16 11:53

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_reviews_average'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='ratings',
        ),
        migrations.AddField(
            model_name='teacher',
            name='ratings',
            field=jsonfield.fields.JSONField(default={'1': 0, '2': 0, '3': 0, '4': 0, '5': 0}),
        ),
    ]
