# Generated by Django 2.1.7 on 2019-03-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0009_auto_20190316_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='average',
            new_name='rating',
        ),
    ]
